### PR TITLE
Content-type, content-length headers were added to sdkResponse

### PR DESCRIPTION
**Pull request by IIVat**
Fix for issue https://github.com/matsluni/aws-spi-akka-http/issues/42

### CODE REVIEW

**Comment by IIVat** [comment]
Hello @matsluni . The issue with content-length https://github.com/matsluni/aws-spi-akka-http/issues/42 doesn't allow to release some of changes in my project. So  I would very appreciate if you could have a look to the PR. Thank you :)

**Comment by matsluni** [comment]
@IIVat Thanks for your investigation and the PR. 🎉  

Are you able to also add a test reproducer which fails without your change and succeeds with the fix? That would be very be very much appreciated.

**Comment by IIVat** [comment]
@matsluni sure, I will take care of it

**Comment by IIVat** [comment]
@matsluni it seems that to write a test reproducer which fails without my changes requires more efforts than I thought. As you mentioned in https://github.com/matsluni/aws-spi-akka-http/issues/42 the SdkClientException "Unable to execute HTTP request: Service returned null 'Content-Length'." is thrown by the chunk of code [https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/EnableTrailingChecksumInterceptor.java#L65](link):
```
    /**
     * Subtract the contentLength of {@link GetObjectResponse} if trailing checksums is enabled.
     */
    @Override
    public SdkResponse modifyResponse(Context.ModifyResponse context, ExecutionAttributes executionAttributes) {
        SdkResponse response = context.response();
        SdkHttpResponse httpResponse = context.httpResponse();

        if (getObjectChecksumEnabledPerResponse(context.request(), httpResponse)) {
            GetObjectResponse getResponse = (GetObjectResponse) response;
            Long contentLength = getResponse.contentLength();
            Validate.notNull(contentLength, "Service returned null 'Content-Length'.");
            return getResponse.toBuilder()
                              .contentLength(contentLength - S3_MD5_CHECKSUM_LENGTH)
                              .build();
        }

        return response;
    }
```
As you can see the main condition for getting inside the if clause is the checksum on response must be enabled. So the response must contain the header `CHECKSUM_ENABLED_RESPONSE_HEADER = x-amz-transfer-encoding` with value `ENABLE_MD5_CHECKSUM_HEADER_VALUE = append-md5` https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java#L160. But s3mock `adobe/s3mock:2.1.24`, which is used in testing, doesn't send the header. I checked a source code of the mock. Without the header the issue cannot be reproduced in the test. What do you think about?

**Comment by matsluni** [comment]
@IIVat, I am really stupid. :facepalm: The test I was asking for is already in place, look here: https://github.com/matsluni/aws-spi-akka-http/blob/master/src/it/scala/com/github/matsluni/akkahttpspi/s3/ITTestS3.scala#L38. We can use this integration test.

This tests now also works, if `checksumValidationEnabled` is `true`. Do you want to add this change to the PR? I think once this is changed we are good to go.

Many thanks again for your fix. It makes totally sense to add the two headers from the Http-Entity. But I am also puzzled that all the other things worked at all, without those two headers in place :-D

**Comment by IIVat** [comment]
@matsluni Ah, sorry, my bad. I didn't have a look to the it-test. Many thanks for the point! Surely, I will add the changes :-)

**Comment by matsluni** [comment]
@IIVat, thanks for this comprehensive commit. It is not quite what I was expecting and goes a little bit to far in my opinion. I like that you want to test, that the headers from `HttpEntity` are read correctly, but I would do the actual implementation a bit different. What do you think about my proposed changes below?

1. Change in `RequestRunner`

```
class RequestRunner()(implicit ec: ExecutionContext, mat: Materializer) {
  val logger = LoggerFactory.getLogger(this.getClass)

  def run(runRequest: () => Future[HttpResponse],
          handler: SdkAsyncHttpResponseHandler): CompletableFuture[Void] = {
```

So, the `run` method gets a function, which when triggered returns a `Future[HttpResponse]`.

2. With the changes in `RequestRunner` the changes in `AkkaHttpClient` would be

```
...
lazy val runner = new RequestRunner()

override def execute(request: AsyncExecuteRequest): CompletableFuture[Void] = {
    val akkaHttpRequest = toAkkaRequest(request.request(), request.requestContentPublisher())
    runner.run(() => Http().singleRequest(akkaHttpRequest, settings = connectionSettings), request.responseHandler())
}
...
```

Then you can write a test like the following:
```
"Check headers are present from response" in {
      implicit val system = ActorSystem("test")
      implicit val ec = system.dispatcher
      val response = HttpResponse(entity = HttpEntity("Ok"), headers = `User-Agent`("Mozilla") :: Nil)
      val runner = new RequestRunner()
      val handler = new MyHeaderHandler()
      val resp = runner.run(() => Future.successful(response), handler)
      resp.join()

      handler.responseHeaders.headers().asScala.get("User-Agent").value.asScala.headOption.value shouldBe "Mozilla"
      handler.responseHeaders.headers().asScala.get("Content-Type").value.asScala.headOption.value shouldBe "text/plain; charset=UTF-8"
      handler.responseHeaders.headers().asScala.get("Content-Length").value.asScala.headOption.value shouldBe "2"
    }

class MyHeaderHandler() extends SdkAsyncHttpResponseHandler {
    private val headers = new AtomicReference[SdkHttpResponse](null)
    def responseHeaders = headers.get()
    override def onHeaders(headers: SdkHttpResponse): Unit = this.headers.set(headers)
    override def onStream(stream: Publisher[ByteBuffer]): Unit = stream.subscribe(new Subscriber[ByteBuffer] {
      override def onSubscribe(s: Subscription): Unit = s.request(1000)
      override def onNext(t: ByteBuffer): Unit = ()
      override def onError(t: Throwable): Unit = ()
      override def onComplete(): Unit = ()
    })
    override def onError(error: Throwable): Unit = ()
  }
```

With this tested you can also just switch the flag here https://github.com/matsluni/aws-spi-akka-http/blob/master/src/it/scala/com/github/matsluni/akkahttpspi/s3/ITTestS3.scala#L38 and we tested everything. I think it is also enough that we test the happy path here. The test you introduced where you test this with a "customized" client with wrong (current) behaviour is not necessary in my opinion.

I hope my proposed changes were described in a understandle way. If something remains unclear please just get back to me.
What do you think about my proposal?

Many thanks for your efforts and your patience with me. :-)

**Comment by IIVat** [comment]
@matsluni, thanks for the thorough review. I like your propositions, it makes sense . I will make the changes.

**Comment by IIVat** [comment]
@matsluni I made the changes as you ask. I added unit test asked by you and enabled checksum in it-test for S3. Thank you for your patience and hope the last code modification is closer to optimal :-)

**Comment by matsluni** [comment]
Awesome job! Thanks for your contribution! :rocket: :tada:

**Pull request merged**
